name 'jenkinsme'
maintainer 'Thomas Holt'
maintainer_email 'twh@pobox.com'
license 'MIT'
description 'Installs jenkins on CentOS'
long_description 'Installs jenkins on CentOS.'
issues_url 'https://github.com/indygwyn/jenkinsme/issues'
source_url 'https://github.com/indygwyn/jenkinsme'
version '0.1.0'
chef_version '>= 13.0'
supports 'centos7'
depends 'java'
depends 'ark'
depends 'yumgroup'
